import { test } from 'node:test';
import { strict as assert } from 'node:assert';

import { toCamelCaseKey, detectMediaType, parseAddAssetArgs, patchAssetsFile, listExistingKeys } from './add-asset';

const FIXTURE_BASE = `// Auto-generated by scripts/migrate-to-blob.ts
// Vercel Blob URLs for all static assets — do not edit manually

export const assets = {
  // Brand
  logo: 'https://abc.public.blob.vercel-storage.com/prax/logo.jpg',
  logoX: 'https://abc.public.blob.vercel-storage.com/prax/logoX.jpg',
} as const;

// Re-export for backward compatibility during migration
export const cloudinaryAssets = assets;
`;

// Sanity test
test('test harness works', () => {
  assert.equal(1 + 1, 2);
});

// ---------- toCamelCaseKey ----------

test('toCamelCaseKey: simple kebab', () => {
  assert.equal(toCamelCaseKey('jack-new-cut.jpg'), 'jackNewCut');
});

test('toCamelCaseKey: with underscores', () => {
  assert.equal(toCamelCaseKey('hero_video_v2.mp4'), 'heroVideoV2');
});

test('toCamelCaseKey: with spaces (treated like separators)', () => {
  assert.equal(toCamelCaseKey('Studio Walkthrough.mp4'), 'studioWalkthrough');
});

test('toCamelCaseKey: mixed separators', () => {
  assert.equal(toCamelCaseKey('Portfolio - 08 - Final.jpg'), 'portfolio08Final');
});

test('toCamelCaseKey: ignores extension', () => {
  assert.equal(toCamelCaseKey('logo.png'), 'logo');
  assert.equal(toCamelCaseKey('logo.jpeg'), 'logo');
});

test('toCamelCaseKey: full path is OK', () => {
  assert.equal(toCamelCaseKey('/home/user/Pictures/jack-new.jpg'), 'jackNew');
});

test('toCamelCaseKey: numbers are kept', () => {
  assert.equal(toCamelCaseKey('image-01.jpg'), 'image01');
});

test('toCamelCaseKey: throws on empty result', () => {
  assert.throws(() => toCamelCaseKey('.jpg'));
  assert.throws(() => toCamelCaseKey('___.jpg'));
});

test('toCamelCaseKey: starts with letter (not number)', () => {
  assert.equal(toCamelCaseKey('123-team.jpg'), 'asset123Team');
});

// ---------- detectMediaType ----------

test('detectMediaType: image extensions', () => {
  assert.equal(detectMediaType('photo.jpg'), 'image');
  assert.equal(detectMediaType('photo.JPEG'), 'image');
  assert.equal(detectMediaType('photo.png'), 'image');
  assert.equal(detectMediaType('photo.webp'), 'image');
  assert.equal(detectMediaType('photo.heic'), 'image');
});

test('detectMediaType: video extensions', () => {
  assert.equal(detectMediaType('video.mp4'), 'video');
  assert.equal(detectMediaType('video.MOV'), 'video');
  assert.equal(detectMediaType('video.webm'), 'video');
});

test('detectMediaType: throws on unknown', () => {
  assert.throws(() => detectMediaType('document.pdf'));
  assert.throws(() => detectMediaType('archive.zip'));
  assert.throws(() => detectMediaType('noext'));
});

// ---------- parseAddAssetArgs ----------

test('parseAddAssetArgs: single positional', () => {
  const result = parseAddAssetArgs(['./photo.jpg']);
  assert.deepEqual(result, {
    filePath: './photo.jpg',
    key: undefined,
    type: undefined,
    force: false,
    dryRun: false,
  });
});

test('parseAddAssetArgs: with --key', () => {
  const result = parseAddAssetArgs(['./photo.jpg', '--key', 'teamJack2']);
  assert.equal(result.key, 'teamJack2');
});

test('parseAddAssetArgs: with --type', () => {
  const result = parseAddAssetArgs(['./video.mp4', '--type', 'video']);
  assert.equal(result.type, 'video');
});

test('parseAddAssetArgs: --type validates value', () => {
  assert.throws(() => parseAddAssetArgs(['./x.jpg', '--type', 'audio']));
});

test('parseAddAssetArgs: --force and --dry-run', () => {
  const result = parseAddAssetArgs(['./x.jpg', '--force', '--dry-run']);
  assert.equal(result.force, true);
  assert.equal(result.dryRun, true);
});

test('parseAddAssetArgs: throws on missing file', () => {
  assert.throws(() => parseAddAssetArgs([]));
  assert.throws(() => parseAddAssetArgs(['--key', 'foo']));
});

// ---------- listExistingKeys / patchAssetsFile ----------

test('listExistingKeys: returns all keys from the assets object', () => {
  const keys = listExistingKeys(FIXTURE_BASE);
  assert.deepEqual(keys, ['logo', 'logoX']);
});

test('listExistingKeys: handles empty object', () => {
  const empty = `export const assets = {} as const;`;
  assert.deepEqual(listExistingKeys(empty), []);
});

test('patchAssetsFile: creates manually-added section if absent', () => {
  const result = patchAssetsFile(FIXTURE_BASE, 'newPhoto', 'https://blob.example/x.jpg');
  assert.match(result, /\/\/ Manually added \(via add-asset\)/);
  assert.match(result, /newPhoto: 'https:\/\/blob\.example\/x\.jpg',/);
  // Order: existing keys, then manual section, then closing brace
  const manualIdx = result.indexOf('// Manually added');
  const closingIdx = result.indexOf('} as const');
  const logoIdx = result.indexOf('logo:');
  assert.ok(logoIdx < manualIdx, 'manual section comes after existing keys');
  assert.ok(manualIdx < closingIdx, 'manual section comes before closing brace');
});

test('patchAssetsFile: appends to existing manually-added section', () => {
  const fixture = FIXTURE_BASE.replace(
    "logoX: 'https://abc.public.blob.vercel-storage.com/prax/logoX.jpg',\n} as const;",
    `logoX: 'https://abc.public.blob.vercel-storage.com/prax/logoX.jpg',

  // Manually added (via add-asset)
  firstAdded: 'https://blob.example/first.jpg',
} as const;`
  );

  const result = patchAssetsFile(fixture, 'secondAdded', 'https://blob.example/second.jpg');
  const matches = result.match(/\/\/ Manually added \(via add-asset\)/g);
  assert.equal(matches?.length, 1, 'section header appears exactly once');
  assert.match(result, /firstAdded: 'https:\/\/blob\.example\/first\.jpg',/);
  assert.match(result, /secondAdded: 'https:\/\/blob\.example\/second\.jpg',/);
  assert.ok(result.indexOf('firstAdded') < result.indexOf('secondAdded'));
});

test('patchAssetsFile: throws on duplicate key without force', () => {
  assert.throws(
    () => patchAssetsFile(FIXTURE_BASE, 'logo', 'https://blob.example/x.jpg'),
    /already exists/
  );
});

test('patchAssetsFile: replaces value when force=true', () => {
  const result = patchAssetsFile(FIXTURE_BASE, 'logo', 'https://blob.example/new.jpg', { force: true });
  assert.match(result, /logo: 'https:\/\/blob\.example\/new\.jpg',/);
  assert.doesNotMatch(result, /logo: 'https:\/\/abc\.public\.blob\.vercel-storage\.com\/prax\/logo\.jpg'/);
});

test('patchAssetsFile: preserves cloudinaryAssets re-export line', () => {
  const result = patchAssetsFile(FIXTURE_BASE, 'newPhoto', 'https://blob.example/x.jpg');
  assert.match(result, /export const cloudinaryAssets = assets;/);
});
